version: '3.8'

services:
  worksout-api:
    container_name: worksout-api
    image: ${{DOCKERHUB_USERNAME}}/worksout:latest
    restart: always

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      # 나중에 DB 붙이면 여기다가 DB URL, USER 등 추가하면 됨

    # 필요해지면 로그/파일 마운트도 이렇게 추가 가능
    # volumes:
    #   - ./logs:/app/logs
    